function y = fir_hp(x)
%FIR_HP Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 11-Nov-2021 21:20:07

%#codegen

% To generate C/C++ code from this function use the codegen command. Type
% 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    % % FIR Window Highpass filter designed using the FIR1 function.
    %
    % % All frequency values are in Hz.
    % Fs = 44100;  % Sampling Frequency
    %
    % Fstop = 5000;     % Stopband Frequency
    % Fpass = 11000;    % Passband Frequency
    % Dstop = 0.01;     % Stopband Attenuation
    % Dpass = 0.01;     % Passband Ripple
    % flag  = 'scale';  % Sampling Flag
    %
    % % Calculate the order from the parameters using KAISERORD.
    % [N,Wn,BETA,TYPE] = kaiserord([Fstop Fpass]/(Fs/2), [0 1], [Dpass Dstop]);
    %
    % % Calculate the coefficients using the FIR1 function.
    % b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
    
    Hd = dsp.FIRFilter( ...
        'Numerator', [0.00388910211955459 -0.00303472257193064 ...
        -0.0168005951241038 -0.014001439116711 0.0220834233156712 ...
        0.0589735264575927 0.0248664971494041 -0.113008434409143 ...
        -0.28527552346347 0.639667947274495 -0.28527552346347 -0.113008434409143 ...
        0.0248664971494041 0.0589735264575927 0.0220834233156712 ...
        -0.014001439116711 -0.0168005951241038 -0.00303472257193064 ...
        0.00388910211955459]);
end

y = step(Hd,double(x));


% [EOF]
