function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 11-Nov-2021 21:41:53

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop = 5000;   % Stopband Frequency
    % Fpass = 11000;  % Passband Frequency
    % Astop = 80;     % Stopband Attenuation (dB)
    % Apass = 1;      % Passband Ripple (dB)
    % Fs    = 44100;  % Sampling Frequency
    %
    % h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    %
    % Hd = design(h, 'cheby2', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.53490085649775 1 1 -0.354525568631229 ...
        0.674697700009911; 1 -1.68794308400119 1 1 -0.316852410263001 ...
        0.281886232693728; 1 -1.89840849677216 1 1 -0.320012979535984 ...
        0.086842491319049; 1 -1 0 1 -0.162506084148242 0], ...
        'ScaleValues', [0.574053799814804; 0.433504153003955; ...
        0.360879438883815; 0.581253042074121; 1]);
end

s = double(x);
y = step(Hd,s);

