function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 11-Nov-2021 21:52:06

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 5000;   % Passband Frequency
    % Fstop = 11000;  % Stopband Frequency
    % Apass = 1;      % Passband Ripple (dB)
    % Astop = 80;     % Stopband Attenuation (dB)
    % Fs    = 44100;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'cheby2', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0.0436527520506196 1 1 -1.13163682615233 ...
        0.737863452101543; 1 0.475813596926791 1 1 -0.868017936911093 ...
        0.379861757844633; 1 1.3624720101516 1 1 -0.700510049807419 ...
        0.172917925286919; 1 1 0 1 -0.320471849927796 0], ...
        'ScaleValues', [0.296638763772816; 0.206737624176912; ...
        0.140494217960256; 0.339764075036102; 1]);
end

s = double(x);
y = step(Hd,s);

